// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";
import { TableEditor } from "../pages/TableEditor";

const toastMock = vi.hoisted(() => ({
  success: vi.fn(),
  error: vi.fn()
}));

vi.mock("sonner", () => ({
  toast: toastMock
}));

const LONG_QUALIFIED_NAME =
  "dataforai.superstore_orders_with_a_very_long_business_name_for_layout_regression";
const OVERLAY_TOOLTIP = "修改将写入独立 overlay 文件：semantic-layer/mysql-aliyun/superstore_orders.yaml";

function renderEditor() {
  const client = new QueryClient({
    defaultOptions: {
      queries: { retry: false }
    }
  });

  render(
    <QueryClientProvider client={client}>
      <MemoryRouter initialEntries={["/sources/mysql-aliyun/dataforai/superstore_orders"]}>
        <Routes>
          <Route path="/sources/:conn/:schema/:table" element={<TableEditor />} />
        </Routes>
      </MemoryRouter>
    </QueryClientProvider>
  );
}

function buildSourceDetail() {
  return {
    model: {
      conn: "mysql-aliyun",
      schema: "dataforai",
      table: "superstore_orders",
      filePath: "semantic-layer/mysql-aliyun/_schema/dataforai.yaml",
      qualifiedName: LONG_QUALIFIED_NAME,
      descriptions: {
        human: "Aggregate order rows for revenue analytics",
        ai: "AI-suggested table description"
      },
      grain: ["order_key"],
      columns: [
        {
          name: "order_key",
          type: "string",
          pk: true,
          nullable: false,
          descriptions: {
            ai: "Business key grouping multiple line items belonging to one order."
          }
        },
        {
          name: "row_id",
          type: "string",
          pk: true,
          nullable: false,
          descriptions: {
            human: "Unique row identifier",
            ai: "Unique row identifier generated by the source system."
          }
        },
        {
          name: "order_date",
          type: "time",
          nullable: true,
          descriptions: {
            ai: "Date when the order was placed."
          }
        }
      ],
      measures: [{ name: "total_sales", expr: "sum(sales)", description: "Total sales" }],
      segments: [],
      joins: [],
      unknownKeys: []
    },
    rawYaml: "table: dataforai.superstore_orders\n",
    completion: "partial"
  };
}

type FetchHandlers = {
  failSave?: boolean;
  failPreview?: boolean;
  candidates?: unknown;
};

function stubEditorFetch({ failSave = false, failPreview = false, candidates }: FetchHandlers = {}) {
  const fetchMock = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
    const url = String(input);
    if (url === "/api/sources") {
      return new Response(
        JSON.stringify({
          ok: true,
          data: {
            tables: [
              {
                conn: "mysql-aliyun",
                schema: "dataforai",
                table: "superstore_orders",
                filePath: "semantic-layer/mysql-aliyun/_schema/dataforai.yaml",
                columnCount: 3,
                columnNames: ["order_key", "row_id", "order_date"],
                hasTableDesc: true,
                hasGrain: true,
                measureCount: 1,
                joinCount: 0,
                wikiRefCount: 0,
                completion: "partial",
                mtime: "2026-06-15T00:00:00.000Z"
              }
            ]
          }
        })
      );
    }
    if (url === "/api/sources/mysql-aliyun/dataforai/superstore_orders" && !init) {
      return new Response(JSON.stringify({ ok: true, data: buildSourceDetail() }));
    }
    if (url === "/api/joins/candidates" && (!init || init.method === undefined)) {
      return new Response(
        JSON.stringify({
          ok: true,
          data: {
            version: 1,
            candidates: candidates ?? []
          }
        })
      );
    }
    if (url === "/api/sources/mysql-aliyun/dataforai/superstore_orders" && init?.method === "PUT") {
      const body = JSON.parse(String(init.body));
      if (body.dryRun) {
        if (failPreview) {
          return new Response(
            JSON.stringify({ ok: false, error: { code: "PREVIEW_FAILED", message: "preview denied" } }),
            { status: 500 }
          );
        }
        return new Response(
          JSON.stringify({
            ok: true,
            data: {
              diff: "+ human: Human column description",
              proposedYaml: "proposed",
              files: [
                {
                  filePath: "semantic-layer/mysql-aliyun/superstore_orders.yaml",
                  diff: "+ human",
                  proposedYaml: "proposed"
                }
              ]
            }
          })
        );
      }
      if (failSave) {
        return new Response(
          JSON.stringify({ ok: false, error: { code: "SAVE_FAILED", message: "disk denied" } }),
          { status: 500 }
        );
      }
      return new Response(
        JSON.stringify({
          ok: true,
          data: {
            written: true,
            validation: { ok: true, exitCode: 0, stdout: "", stderr: "" },
            changedFiles: []
          }
        })
      );
    }
    if (url === "/api/joins/candidates" && init?.method === "PUT") {
      const body = JSON.parse(String(init.body));
      return new Response(
        JSON.stringify({
          ok: true,
          data: {
            version: 1,
            candidates: body.candidates ?? []
          }
        })
      );
    }
    return new Response(
      JSON.stringify({ ok: false, error: { code: "NOT_FOUND", message: url } }),
      { status: 404 }
    );
  });
  vi.stubGlobal("fetch", fetchMock);
  return fetchMock;
}

afterEach(() => {
  cleanup();
  toastMock.success.mockClear();
  toastMock.error.mockClear();
  vi.restoreAllMocks();
  vi.unstubAllGlobals();
});

describe("TableEditor", () => {
  it("renders metadata grid and human description from source, not from AI", async () => {
    stubEditorFetch();
    renderEditor();

    expect(await screen.findByText("维护表语义：superstore_orders")).toBeInTheDocument();
    // The human description populates the table description textarea; AI does not.
    const tableTextarea = await screen.findByDisplayValue("Aggregate order rows for revenue analytics");
    expect(tableTextarea).toBeInTheDocument();
    // AI table description should not silently fill the human textarea.
    expect(screen.queryByDisplayValue("AI-suggested table description")).not.toBeInTheDocument();
  });

  it("renders stable metadata grid with truncation and copy button", async () => {
    stubEditorFetch();
    Object.assign(navigator, { clipboard: { writeText: vi.fn().mockResolvedValue(undefined) } });
    renderEditor();

    const copyButton = await screen.findByRole("button", { name: "复制完整表名" });
    fireEvent.click(copyButton);
    expect(navigator.clipboard.writeText).toHaveBeenCalledWith(LONG_QUALIFIED_NAME);

    // Truncated long name still has a title tooltip
    const truncated = screen.getByTitle(LONG_QUALIFIED_NAME);
    expect(truncated).toBeInTheDocument();
    expect(truncated).toHaveClass("truncate");
  });

  it("renders field cards with badges and Adopt AI button", async () => {
    stubEditorFetch();
    renderEditor();

    fireEvent.click(screen.getByRole("button", { name: /^字段/ }));

    // Wait for the columns section to actually render before asserting on
    // its cards (the grain field on the overview tab also contains the
    // column name "order_key" so we cannot use it as a readiness signal).
    await screen.findByText("字段语义");

    expect(screen.getByText("order_key")).toBeInTheDocument();
    // Metadata badges
    expect(screen.getAllByText("PK").length).toBeGreaterThan(0);
    expect(screen.getAllByText("string").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Not Null").length).toBeGreaterThan(0);
    // AI text is visible (read-only)
    expect(screen.getByText(/Business key grouping/)).toBeInTheDocument();
    // Adopt AI buttons exist (one per column that has AI; fixture has 2)
    const adoptButtons = screen.getAllByRole("button", { name: /采纳 AI 描述|覆盖为 AI 描述/ });
    expect(adoptButtons.length).toBeGreaterThan(0);
    // Critical: AI must NOT be silently pre-filled into Human textarea on initial render
    expect(
      screen.queryByDisplayValue("Business key grouping multiple line items belonging to one order.")
    ).not.toBeInTheDocument();
  });

  it("adopts AI description into Human textarea and writes human in dry-run patch", async () => {
    const fetchMock = stubEditorFetch();
    renderEditor();

    fireEvent.click(screen.getByRole("button", { name: /^字段/ }));
    await screen.findByText("字段语义");

    // The first Adopt button belongs to order_key (the first card with AI
    // and an empty human description).
    const adoptButtons = await screen.findAllByRole("button", { name: /采纳 AI 描述/ });
    expect(adoptButtons.length).toBeGreaterThan(0);
    fireEvent.click(adoptButtons[0]);

    // After click, Human textarea now contains the AI text
    expect(
      await screen.findByDisplayValue(
        "Business key grouping multiple line items belonging to one order."
      )
    ).toBeInTheDocument();

    // Dry-run patch writes only descriptions.human (not the AI bucket)
    await waitFor(() => {
      const putCall = fetchMock.mock.calls.find(
        (call) =>
          call[1]?.method === "PUT" &&
          JSON.parse(String(call[1]?.body)).dryRun === true &&
          JSON.parse(String(call[1]?.body)).patch.columns?.some(
            (column: { name: string; description: string }) =>
              column.name === "order_key" &&
              column.description === "Business key grouping multiple line items belonging to one order."
          )
      );
      expect(putCall).toBeTruthy();
      const body = JSON.parse(String(putCall?.[1]?.body));
      expect(body.dryRun).toBe(true);
      expect(body.patch.columns).toContainEqual({
        name: "order_key",
        description: "Business key grouping multiple line items belonging to one order."
      });
    });
  });

  it("does not write empty Human descriptions for untouched AI-only fields", async () => {
    const fetchMock = stubEditorFetch();
    renderEditor();

    await screen.findByText("维护表语义：superstore_orders");

    await waitFor(() => {
      const dryRunCall = fetchMock.mock.calls.find(
        (call) => call[1]?.method === "PUT" && JSON.parse(String(call[1]?.body)).dryRun === true
      );
      expect(dryRunCall).toBeTruthy();
      const body = JSON.parse(String(dryRunCall?.[1]?.body));
      expect(body.patch.tableDescription).toBeUndefined();
      expect(body.patch.columns).toBeUndefined();
    });
  });

  it("renders Overlay badges with resolved overlay path tooltip", async () => {
    stubEditorFetch();
    renderEditor();

    // The overview page already exposes overlay badge for grain and the table grain metadata
    expect(await screen.findAllByText("Overlay")).not.toHaveLength(0);
    // The tooltip should resolve to a concrete overlay path. There can be
    // more than one (grain metadata + grain input) so use getAllByTitle.
    expect(
      screen.getAllByTitle(
        "修改将写入独立 overlay 文件：semantic-layer/mysql-aliyun/superstore_orders.yaml"
      ).length
    ).toBeGreaterThan(0);

    // Measures section also exposes the overlay badge
    fireEvent.click(screen.getByRole("button", { name: /^Measures/ }));
    expect((await screen.findAllByText("Overlay")).length).toBeGreaterThan(0);
    // Segments section too
    fireEvent.click(screen.getByRole("button", { name: /^Segments/ }));
    expect(screen.getAllByText("Overlay").length).toBeGreaterThan(0);
  });

  it("embeds candidate join banner with three action buttons", async () => {
    stubEditorFetch({
      candidates: [
        {
          conn: "mysql-aliyun",
          schema: "dataforai",
          fromTable: "superstore_orders",
          join: {
            to: "rows",
            on: "superstore_orders.row_id = rows.row_id",
            relationship: "many_to_one",
            source: "candidate"
          },
          confidence: "candidate",
          note: "字段名匹配"
        }
      ]
    });
    renderEditor();

    expect(await screen.findByText(/发现 1 个智能推断的候选关联关系/)).toBeInTheDocument();
    expect(screen.getByText("rows")).toBeInTheDocument();
    expect(screen.getByText("superstore_orders.row_id = rows.row_id")).toBeInTheDocument();
    expect(screen.getByText(/推断依据: 字段名匹配/)).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "确认写入语义层" })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "保留为候选" })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "标记不采用" })).toBeInTheDocument();
  });

  it("does not show sidecar candidates for another source table", async () => {
    stubEditorFetch({
      candidates: [
        {
          conn: "mysql-aliyun",
          schema: "dataforai",
          fromTable: "superstore_returns",
          join: {
            to: "return_reasons",
            on: "superstore_returns.reason_id = return_reasons.reason_id",
            relationship: "many_to_one",
            source: "candidate"
          },
          confidence: "candidate",
          note: "字段名匹配"
        }
      ]
    });
    renderEditor();

    expect(await screen.findByText(/发现 1 个智能推断的候选关联关系/)).toBeInTheDocument();
    expect(screen.queryByText("return_reasons")).not.toBeInTheDocument();
    expect(screen.queryByText("superstore_returns.reason_id = return_reasons.reason_id")).not.toBeInTheDocument();
  });

  it("keeps rejected live suggestions out of the prominent candidate banner", async () => {
    stubEditorFetch({
      candidates: [
        {
          conn: "mysql-aliyun",
          schema: "dataforai",
          fromTable: "superstore_orders",
          join: {
            to: "rows",
            on: "superstore_orders.row_id = rows.row_id",
            relationship: "many_to_one",
            source: "candidate"
          },
          confidence: "rejected",
          note: "字段名匹配"
        }
      ]
    });
    renderEditor();

    expect(await screen.findByText("维护表语义：superstore_orders")).toBeInTheDocument();
    await waitFor(() => {
      expect(screen.queryByText(/发现 \d+ 个智能推断的候选关联关系/)).not.toBeInTheDocument();
    });
    expect(screen.queryByText("rows")).not.toBeInTheDocument();
    expect(screen.queryByText("superstore_orders.row_id = rows.row_id")).not.toBeInTheDocument();
  });

  it("rejects a candidate by sending PUT to /api/joins/candidates with confidence rejected", async () => {
    const fetchMock = stubEditorFetch({
      candidates: [
        {
          conn: "mysql-aliyun",
          schema: "dataforai",
          fromTable: "superstore_orders",
          join: {
            to: "rows",
            on: "superstore_orders.row_id = rows.row_id",
            relationship: "many_to_one",
            source: "candidate"
          },
          confidence: "candidate",
          note: "字段名匹配"
        }
      ]
    });
    renderEditor();

    const rejectButton = await screen.findByRole("button", { name: "标记不采用" });
    fireEvent.click(rejectButton);

    await waitFor(() => {
      const putCall = fetchMock.mock.calls.find(
        (call) =>
          call[1]?.method === "PUT" &&
          String(call[0]).endsWith("/api/joins/candidates")
      );
      expect(putCall).toBeTruthy();
      const body = JSON.parse(String(putCall?.[1]?.body));
      expect(body.candidates).toEqual([
        expect.objectContaining({
          conn: "mysql-aliyun",
          schema: "dataforai",
          fromTable: "superstore_orders",
          confidence: "rejected",
          join: expect.objectContaining({
            to: "rows",
            on: "superstore_orders.row_id = rows.row_id",
            relationship: "many_to_one",
            source: "candidate"
          })
        })
      ]);
    });
  });

  it("confirms a candidate as a formal join via PUT /api/sources with dryRun false", async () => {
    const fetchMock = stubEditorFetch({
      candidates: [
        {
          conn: "mysql-aliyun",
          schema: "dataforai",
          fromTable: "superstore_orders",
          join: {
            to: "rows",
            on: "superstore_orders.row_id = rows.row_id",
            relationship: "many_to_one",
            source: "candidate"
          },
          confidence: "candidate",
          note: "字段名匹配"
        }
      ]
    });
    renderEditor();

    const confirmButton = await screen.findByRole("button", { name: "确认写入语义层" });
    fireEvent.click(confirmButton);

    await waitFor(() => {
      const putCall = fetchMock.mock.calls.find(
        (call) =>
          call[1]?.method === "PUT" &&
          String(call[0]).endsWith("/api/sources/mysql-aliyun/dataforai/superstore_orders") &&
          JSON.parse(String(call[1]?.body)).dryRun === false
      );
      expect(putCall).toBeTruthy();
      const body = JSON.parse(String(putCall?.[1]?.body));
      expect(body).toEqual({
        dryRun: false,
        patch: {
          joins: expect.arrayContaining([
            expect.objectContaining({
              to: "rows",
              on: "superstore_orders.row_id = rows.row_id",
              relationship: "many_to_one",
              source: "formal"
            })
          ])
        }
      });
    });
  });

  it("Cmd+S triggers DryRun and switches to Diff tab, never saves", async () => {
    const fetchMock = stubEditorFetch();
    renderEditor();

    // Switch to columns section first so the form has something to dry-run
    fireEvent.click(screen.getByRole("button", { name: /^字段/ }));
    await screen.findByText("字段语义");
    expect(screen.getByText("order_key")).toBeInTheDocument();

    // Find the form root to focus inside
    const form = document.getElementById("table-editor-form");
    expect(form).toBeTruthy();

    // Simulate Cmd+S
    const keyEvent = new KeyboardEvent("keydown", {
      key: "s",
      metaKey: true,
      bubbles: true,
      cancelable: true
    });
    const preventDefaultSpy = vi.spyOn(keyEvent, "preventDefault");
    fireEvent(form as HTMLElement, keyEvent);

    expect(preventDefaultSpy).toHaveBeenCalled();

    // A dry-run PUT should be sent
    await waitFor(() => {
      const dryRunCall = fetchMock.mock.calls.find(
        (call) =>
          call[1]?.method === "PUT" &&
          JSON.parse(String(call[1]?.body)).dryRun === true
      );
      expect(dryRunCall).toBeTruthy();
    });

    // No save with dryRun false should be sent
    const saveCalls = fetchMock.mock.calls.filter((call) => {
      if (call[1]?.method !== "PUT") return false;
      return JSON.parse(String(call[1]?.body)).dryRun === false;
    });
    expect(saveCalls).toHaveLength(0);

    // The Diff tab should be selected
    await waitFor(() => {
      const diffTab = screen.getByRole("tab", { name: "Diff" });
      expect(diffTab).toHaveAttribute("aria-selected", "true");
    });
    expect(toastMock.success).toHaveBeenCalledWith("已更新 Dry-run 预览");
    expect(toastMock.error).not.toHaveBeenCalledWith("Dry-run 预览失败");
  });

  it("Cmd+S reports DryRun failure instead of showing a success toast", async () => {
    stubEditorFetch({ failPreview: true });
    renderEditor();

    await screen.findByText("维护表语义：superstore_orders");
    const form = document.getElementById("table-editor-form");
    expect(form).toBeTruthy();

    fireEvent(
      form as HTMLElement,
      new KeyboardEvent("keydown", {
        key: "s",
        metaKey: true,
        bubbles: true,
        cancelable: true
      })
    );

    expect(await screen.findByText("preview denied")).toBeInTheDocument();
    expect(toastMock.error).toHaveBeenCalledWith("Dry-run 预览失败");
    expect(toastMock.success).not.toHaveBeenCalledWith("已更新 Dry-run 预览");
  });

  it("saves with dryRun false from the page-level save button", async () => {
    const fetchMock = stubEditorFetch();
    renderEditor();

    fireEvent.click(await screen.findByRole("button", { name: "保存" }));

    await waitFor(() => {
      const saveCall = fetchMock.mock.calls.find((call) => {
        if (call[1]?.method !== "PUT") {
          return false;
        }
        return JSON.parse(String(call[1].body)).dryRun === false;
      });
      expect(saveCall).toBeTruthy();
    });
  });

  it("shows save errors in the inspector", async () => {
    stubEditorFetch({ failSave: true });
    renderEditor();

    fireEvent.click(await screen.findByRole("button", { name: "保存" }));

    expect(await screen.findByText("保存失败：disk denied")).toBeInTheDocument();
  });
});
