// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";
import { TableEditor } from "../pages/TableEditor";

const toastMock = vi.hoisted(() => ({
  success: vi.fn(),
  error: vi.fn()
}));

vi.mock("sonner", () => ({
  toast: toastMock
}));

const LONG_QUALIFIED_NAME =
  "dataforai.superstore_orders_with_a_very_long_business_name_for_layout_regression";
const OVERLAY_TOOLTIP = "修改将写入独立 overlay 文件：semantic-layer/mysql-aliyun/superstore_orders.yaml";

function renderEditor(path = "/catalog/mysql-aliyun/dataforai/superstore_orders") {
  const client = new QueryClient({
    defaultOptions: {
      queries: { retry: false }
    }
  });

  render(
    <QueryClientProvider client={client}>
      <MemoryRouter initialEntries={[path]}>
        <Routes>
          <Route path="/catalog/:conn/:schema/:table" element={<TableEditor />} />
        </Routes>
      </MemoryRouter>
    </QueryClientProvider>
  );
}

async function openManualSemanticEditor() {
  return screen.findByTestId("semantic-content");
}

function buildSourceDetail() {
  return {
    model: {
      conn: "mysql-aliyun",
      schema: "dataforai",
      table: "superstore_orders",
      filePath: "semantic-layer/mysql-aliyun/_schema/dataforai.yaml",
      qualifiedName: LONG_QUALIFIED_NAME,
      descriptions: {
        human: "Aggregate order rows for revenue analytics",
        ai: "AI-suggested table description"
      },
      grain: ["order_key"],
      columns: [
        {
          name: "order_key",
          type: "string",
          pk: true,
          nullable: false,
          descriptions: {
            db: "订单行 ID",
            ai: "Business key grouping multiple line items belonging to one order."
          }
        },
        {
          name: "row_id",
          type: "string",
          pk: true,
          nullable: false,
          descriptions: {
            human: "Unique row identifier",
            ai: "Unique row identifier generated by the source system."
          }
        },
        {
          name: "order_date",
          type: "time",
          nullable: true,
          descriptions: {
            ai: "Date when the order was placed."
          }
        }
      ],
      measures: [{ name: "total_sales", expr: "sum(sales)", description: "Total sales" }],
      segments: [],
      joins: [],
      unknownKeys: []
    },
    rawYaml: "table: dataforai.superstore_orders\n",
    completion: "partial"
  };
}

type FetchHandlers = {
  failSave?: boolean;
  failPreview?: boolean;
  candidates?: unknown;
};

function stubEditorFetch({ failSave = false, failPreview = false, candidates }: FetchHandlers = {}) {
  const fetchMock = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
    const url = String(input);
    if (url === "/api/sources") {
      return new Response(
        JSON.stringify({
          ok: true,
          data: {
            tables: [
              {
                conn: "mysql-aliyun",
                schema: "dataforai",
                table: "superstore_orders",
                filePath: "semantic-layer/mysql-aliyun/_schema/dataforai.yaml",
                columnCount: 3,
                columnNames: ["order_key", "row_id", "order_date"],
                hasTableDesc: true,
                hasGrain: true,
                measureCount: 1,
                joinCount: 0,
                wikiRefCount: 0,
                completion: "partial",
                mtime: "2026-06-15T00:00:00.000Z"
              }
            ]
          }
        })
      );
    }
    if (url === "/api/sources/mysql-aliyun/dataforai/superstore_orders" && !init) {
      return new Response(JSON.stringify({ ok: true, data: buildSourceDetail() }));
    }
    if (url === "/api/joins/candidates" && (!init || init.method === undefined)) {
      return new Response(
        JSON.stringify({
          ok: true,
          data: {
            version: 1,
            candidates: candidates ?? []
          }
        })
      );
    }
    if (url === "/api/sources/mysql-aliyun/dataforai/superstore_orders" && init?.method === "PUT") {
      const body = JSON.parse(String(init.body));
      if (body.dryRun) {
        if (failPreview) {
          return new Response(
            JSON.stringify({ ok: false, error: { code: "PREVIEW_FAILED", message: "preview denied" } }),
            { status: 500 }
          );
        }
        return new Response(
          JSON.stringify({
            ok: true,
            data: {
              diff: "+ human: Human column description",
              proposedYaml: "proposed",
              files: [
                {
                  filePath: "semantic-layer/mysql-aliyun/superstore_orders.yaml",
                  diff: "+ human",
                  proposedYaml: "proposed"
                }
              ]
            }
          })
        );
      }
      if (failSave) {
        return new Response(
          JSON.stringify({ ok: false, error: { code: "SAVE_FAILED", message: "disk denied" } }),
          { status: 500 }
        );
      }
      return new Response(
        JSON.stringify({
          ok: true,
          data: {
            written: true,
            validation: { ok: true, exitCode: 0, stdout: "", stderr: "" },
            changedFiles: []
          }
        })
      );
    }
    if (url === "/api/sources/mysql-aliyun/dataforai/superstore_orders/import" && init?.method === "POST") {
      const body = JSON.parse(String(init.body));
      if (body.dryRun) {
        return new Response(
          JSON.stringify({
            ok: true,
            data: {
              diff: "- descriptions:\n+ descriptions:",
              proposedYaml: body.yaml,
              files: [
                {
                  filePath: "semantic-layer/mysql-aliyun/_schema/dataforai.yaml",
                  diff: "- descriptions:\n+ descriptions:",
                  proposedYaml: body.yaml
                }
              ]
            }
          })
        );
      }
      return new Response(
        JSON.stringify({
          ok: true,
          data: {
            written: true,
            validation: { ok: true, exitCode: 0, stdout: "", stderr: "" },
            changedFiles: []
          }
        })
      );
    }
    if (url === "/api/sources/mysql-aliyun/dataforai/superstore_orders/versions" && !init) {
      return new Response(
        JSON.stringify({
          ok: true,
          data: {
            key: "mysql-aliyun/dataforai/superstore_orders",
            retentionLimit: 5,
            versions: [
              {
                versionId: "20260615T000000000Z-abcd1234",
                key: "mysql-aliyun/dataforai/superstore_orders",
                createdAt: "2026-06-15T00:00:00.000Z",
                operation: "save",
                contentHash: "sha256:abcdef123456",
                affectedFiles: ["semantic-layer/mysql-aliyun/_schema/dataforai.yaml"]
              }
            ]
          }
        })
      );
    }
    if (url === "/api/sources/mysql-aliyun/dataforai/superstore_orders/versions/20260615T000000000Z-abcd1234" && !init) {
      return new Response(
        JSON.stringify({
          ok: true,
          data: {
            versionId: "20260615T000000000Z-abcd1234",
            key: "mysql-aliyun/dataforai/superstore_orders",
            createdAt: "2026-06-15T00:00:00.000Z",
            operation: "save",
            contentHash: "sha256:abcdef123456",
            affectedFiles: ["semantic-layer/mysql-aliyun/_schema/dataforai.yaml"],
            rawYaml: "table: dataforai.superstore_orders\nversion: restored\n",
            diffFromCurrent: "- table: dataforai.superstore_orders\n+ version: restored\n"
          }
        })
      );
    }
    if (url === "/api/sources/mysql-aliyun/dataforai/superstore_orders/versions/20260615T000000000Z-abcd1234/restore" && init?.method === "POST") {
      return new Response(
        JSON.stringify({
          ok: true,
          data: {
            key: "mysql-aliyun/dataforai/superstore_orders",
            restoredFromVersionId: "20260615T000000000Z-abcd1234",
            rawYaml: "table: dataforai.superstore_orders\nversion: restored\n",
            diff: "- table: dataforai.superstore_orders\n+ version: restored\n"
          }
        })
      );
    }
    if (url === "/api/sources/mysql-aliyun/dataforai/superstore_orders/validate" && init?.method === "POST") {
      return new Response(
        JSON.stringify({
          ok: true,
          data: { ok: true, exitCode: 0, stdout: "ok", stderr: "", issues: [] }
        })
      );
    }
    if (url === "/api/joins/candidates" && init?.method === "PUT") {
      const body = JSON.parse(String(init.body));
      return new Response(
        JSON.stringify({
          ok: true,
          data: {
            version: 1,
            candidates: body.candidates ?? []
          }
        })
      );
    }
    return new Response(
      JSON.stringify({ ok: false, error: { code: "NOT_FOUND", message: url } }),
      { status: 404 }
    );
  });
  vi.stubGlobal("fetch", fetchMock);
  return fetchMock;
}

afterEach(() => {
  cleanup();
  toastMock.success.mockClear();
  toastMock.error.mockClear();
  vi.restoreAllMocks();
  vi.unstubAllGlobals();
});

describe("TableEditor", () => {
  it("renders on the canonical /catalog table route", async () => {
    stubEditorFetch();
    renderEditor("/catalog/mysql-aliyun/dataforai/superstore_orders");
    expect(await screen.findByRole("heading", { name: "superstore_orders" })).toBeInTheDocument();
  });

  it("prioritizes online editing and removes the inline import/export section", async () => {
    stubEditorFetch();
    renderEditor();

    const semanticContent = await screen.findByTestId("semantic-content");
    expect(within(semanticContent).getByText("在线编辑")).toBeInTheDocument();
    expect(within(semanticContent).getByRole("tablist", { name: "在线编辑" })).toBeInTheDocument();

    expect(screen.queryByTestId("semantic-asset-exchange")).not.toBeInTheDocument();
    expect(screen.queryByText("导入 / 导出")).not.toBeInTheDocument();
    expect(screen.queryByTestId("table-editor-import-drawer")).not.toBeInTheDocument();
    expect(document.body).not.toHaveTextContent("主流程：导出 YAML");
    expect(document.body).not.toHaveTextContent("Claude Code");
    expect(document.body).not.toHaveTextContent("Codex");
    expect(screen.queryByText("高级：手工维护语义字段")).not.toBeInTheDocument();
    expect(screen.queryByText(/待处理建议/)).not.toBeInTheDocument();
  });

  it("hides the native file input while keeping 导入 YAML as the user-facing entry", async () => {
    stubEditorFetch();
    renderEditor();

    const headerActions = await screen.findByTestId("page-header-actions");
    fireEvent.click(within(headerActions).getByRole("button", { name: "导入 YAML" }));
    const drawer = await screen.findByTestId("table-editor-import-drawer");
    expect(within(drawer).getByRole("button", { name: "选择 YAML 文件" })).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: /Choose File/i })).not.toBeInTheDocument();
    const input = await screen.findByTestId("table-editor-import-input");
    expect(input).toHaveAttribute("aria-hidden", "true");
    expect(input).toHaveAttribute("tabindex", "-1");
  });

  it("uses a single page header action group and keeps secondary links in more", async () => {
    stubEditorFetch();
    renderEditor();

    const headerActions = await screen.findByTestId("page-header-actions");
    expect(screen.queryByTestId("table-editor-command-bar")).not.toBeInTheDocument();
    expect(within(headerActions).getByRole("button", { name: "校验" })).toBeInTheDocument();
    expect(within(headerActions).getByRole("button", { name: "保存" })).toBeInTheDocument();
    expect(screen.getAllByText("导出 YAML")).toHaveLength(1);
    expect(screen.getAllByText("导入 YAML")).toHaveLength(1);
    expect(screen.getAllByRole("button", { name: "校验" })).toHaveLength(1);
    expect(screen.getAllByRole("button", { name: "保存" })).toHaveLength(1);
    expect(within(headerActions).queryByRole("link", { name: "查看关联的业务 Wiki" })).not.toBeInTheDocument();
    expect(within(headerActions).queryByRole("link", { name: "关联关系" })).not.toBeInTheDocument();
    expect(within(headerActions).queryByRole("link", { name: "审阅" })).not.toBeInTheDocument();

    fireEvent.click(within(headerActions).getByTestId("row-more-trigger"));
    const menu = await within(headerActions).findByTestId("row-more-menu");
    expect(within(menu).getByTestId("table-editor-more-versions")).toHaveTextContent("版本记录");
    expect(within(menu).getByTestId("table-editor-more-wiki")).toHaveTextContent("查看关联的业务 Wiki");
    expect(within(menu).getByTestId("table-editor-more-review")).toHaveTextContent("审阅");
    expect(within(menu).getByTestId("table-editor-more-joins")).toHaveTextContent("关联关系");
  });

  it("opens version history and restores a version as an unsaved import draft", async () => {
    const fetchMock = stubEditorFetch();
    renderEditor();

    const headerActions = await screen.findByTestId("page-header-actions");
    fireEvent.click(within(headerActions).getByTestId("row-more-trigger"));
    fireEvent.click(await screen.findByTestId("table-editor-more-versions"));

    const panel = await screen.findByTestId("table-editor-version-panel");
    expect(panel).toHaveTextContent("版本记录");
    expect(await within(panel).findByText("保存")).toBeInTheDocument();
    expect(await within(panel).findByText("abcdef12")).toBeInTheDocument();
    expect(await within(panel).findByText("恢复此版本")).toBeInTheDocument();

    fireEvent.click(within(panel).getByRole("button", { name: "恢复此版本" }));

    await waitFor(() => {
      expect(screen.getByTestId("table-editor-imported-yaml-name")).toHaveTextContent("恢复版本 20260615");
    });
    expect(toastMock.success).toHaveBeenCalledWith("已恢复为未保存草稿");

    fireEvent.click(await screen.findByRole("button", { name: "保存" }));
    await waitFor(() => {
      const restoreSaveCall = fetchMock.mock.calls.find((call) => {
        if (!String(call[0]).endsWith("/api/sources/mysql-aliyun/dataforai/superstore_orders/import")) {
          return false;
        }
        if (call[1]?.method !== "POST") {
          return false;
        }
        const body = JSON.parse(String(call[1].body));
        return body.dryRun === false && body.restoredFromVersionId === "20260615T000000000Z-abcd1234";
      });
      expect(restoreSaveCall).toBeTruthy();
    });
  });

  it("anchors the current table with a compact header and no redundant chips", async () => {
    stubEditorFetch();
    renderEditor();

    expect(await screen.findByRole("heading", { name: "superstore_orders" })).toBeInTheDocument();
    const context = screen.getByTestId("table-editor-header-context");
    expect(context).toHaveTextContent("连接：mysql-aliyun");
    expect(context).toHaveTextContent("Schema：dataforai");
    expect(screen.queryByTestId("page-header-badges")).not.toBeInTheDocument();
    expect(screen.queryByText("完成度 partial")).not.toBeInTheDocument();
    expect(screen.queryByText("导出、导入、校验并审阅当前表的 semantic-layer YAML。")).not.toBeInTheDocument();
  });

  it("renders metadata grid and human description from source, not from AI", async () => {
    stubEditorFetch();
    renderEditor();

    await openManualSemanticEditor();
    expect(await screen.findByRole("heading", { name: "superstore_orders" })).toBeInTheDocument();
    // The human description populates the table description textarea; AI does not.
    const tableTextarea = await screen.findByDisplayValue("Aggregate order rows for revenue analytics");
    expect(tableTextarea).toBeInTheDocument();
    // AI table description should not silently fill the human textarea.
    expect(screen.queryByDisplayValue("AI-suggested table description")).not.toBeInTheDocument();
  });

  it("shows object-level change summary and raw YAML Diff in the sticky review", async () => {
    stubEditorFetch();
    renderEditor();

    await openManualSemanticEditor();
    const tableTextarea = await screen.findByDisplayValue("Aggregate order rows for revenue analytics");
    fireEvent.change(tableTextarea, { target: { value: "Updated order semantics" } });

    const review = await screen.findByTestId("table-editor-change-review");
    const summary = await within(review).findByTestId("change-summary");
    expect(summary).toHaveTextContent("本次变更");
    expect(summary).toHaveTextContent("表描述");
    expect(summary).toHaveTextContent("修改 1");
    expect(summary).toHaveTextContent("Aggregate order rows for revenue analytics -> Updated order semantics");
    expect(within(review).getByRole("tab", { name: "YAML Diff" })).toHaveAttribute("aria-selected", "true");
    expect(within(review).getAllByText("YAML Diff").length).toBeGreaterThan(0);
    expect(screen.queryByTestId("raw-diff-disclosure")).not.toBeInTheDocument();
  });

  it("names the edited field in the change review summary", async () => {
    stubEditorFetch();
    renderEditor();

    await openManualSemanticEditor();
    fireEvent.click(screen.getByRole("tab", { name: /^字段/ }));
    const rowIdTextarea = await screen.findByLabelText("row_id 人工描述");
    fireEvent.change(rowIdTextarea, { target: { value: "这是一个段测试" } });

    const review = await screen.findByTestId("table-editor-change-review");
    const summary = await within(review).findByTestId("change-summary");
    expect(summary).toHaveTextContent("字段描述");
    expect(summary).toHaveTextContent("修改 1");
    expect(summary).toHaveTextContent("字段 row_id · 人工描述：Unique row identifier -> 这是一个段测试");
  });

  it("previews pasted YAML as an import dry-run without saving", async () => {
    const fetchMock = stubEditorFetch();
    renderEditor();

    const headerActions = await screen.findByTestId("page-header-actions");
    fireEvent.click(within(headerActions).getByRole("button", { name: "导入 YAML" }));
    const drawer = await screen.findByTestId("table-editor-import-drawer");
    fireEvent.change(within(drawer).getByTestId("paste-yaml-textarea"), {
      target: { value: "table: dataforai.superstore_orders\n    descriptions:\n      human: Updated from external editor\n" }
    });
    fireEvent.click(within(drawer).getByRole("button", { name: "生成导入预览" }));

    await waitFor(() => {
      const importPreviewCall = fetchMock.mock.calls.find((call) => {
        if (!String(call[0]).endsWith("/api/sources/mysql-aliyun/dataforai/superstore_orders/import")) {
          return false;
        }
        if (call[1]?.method !== "POST") {
          return false;
        }
        const body = JSON.parse(String(call[1].body));
        return body.dryRun === true && String(body.yaml).includes("Updated from external editor");
      });
      expect(importPreviewCall).toBeTruthy();
    });

    expect(await screen.findByTestId("table-editor-imported-yaml-name")).toHaveTextContent("粘贴 YAML");
    const summary = await screen.findByTestId("change-summary");
    expect(summary).toHaveTextContent("导入 YAML");
    const saveCalls = fetchMock.mock.calls.filter((call) => {
      if (!String(call[0]).endsWith("/api/sources/mysql-aliyun/dataforai/superstore_orders/import")) {
        return false;
      }
      if (call[1]?.method !== "POST") {
        return false;
      }
      return JSON.parse(String(call[1].body)).dryRun === false;
    });
    expect(saveCalls).toHaveLength(0);
  });

  it("runs Validate from the page header and shows the result in change details", async () => {
    const fetchMock = stubEditorFetch();
    renderEditor();

    const headerActions = await screen.findByTestId("page-header-actions");
    fireEvent.click(within(headerActions).getByRole("button", { name: "校验" }));

    await waitFor(() => {
      expect(fetchMock).toHaveBeenCalledWith(
        "/api/sources/mysql-aliyun/dataforai/superstore_orders/validate",
        expect.objectContaining({ method: "POST" })
      );
    });
    expect(await screen.findByTestId("table-editor-validation-result")).toHaveTextContent("通过");
  });

  it("clears stale validation after a new import preview", async () => {
    stubEditorFetch();
    renderEditor();

    const headerActions = await screen.findByTestId("page-header-actions");
    fireEvent.click(within(headerActions).getByRole("button", { name: "校验" }));
    expect(await screen.findByTestId("table-editor-validation-result")).toHaveTextContent("通过");
    expect(await screen.findByTestId("table-editor-change-review")).toHaveTextContent("校验通过");

    fireEvent.click(within(headerActions).getByRole("button", { name: "导入 YAML" }));
    const drawer = await screen.findByTestId("table-editor-import-drawer");
    fireEvent.change(within(drawer).getByTestId("paste-yaml-textarea"), {
      target: { value: "table: dataforai.superstore_orders\n    descriptions:\n      human: Updated after validate\n" }
    });
    fireEvent.click(within(drawer).getByRole("button", { name: "生成导入预览" }));

    await waitFor(() => {
      expect(screen.queryByTestId("table-editor-validation-result")).not.toBeInTheDocument();
    });
    expect(screen.getByTestId("table-editor-change-review")).not.toHaveTextContent("校验通过");
  });

  it("keeps duplicate table metadata out of the semantic content overview", async () => {
    stubEditorFetch();
    renderEditor();

    const semanticContent = await openManualSemanticEditor();
    expect(within(semanticContent).queryByText("完整表名")).not.toBeInTheDocument();
    expect(within(semanticContent).queryByText("字段数")).not.toBeInTheDocument();
    expect(within(semanticContent).queryByText("关联数")).not.toBeInTheDocument();
    expect(within(semanticContent).queryByRole("button", { name: "复制完整表名" })).not.toBeInTheDocument();
    expect(await screen.findByDisplayValue("Aggregate order rows for revenue analytics")).toBeInTheDocument();
  });

  it("renders field cards with badges and Adopt AI button", async () => {
    stubEditorFetch();
    renderEditor();

    await openManualSemanticEditor();
    fireEvent.click(screen.getByRole("tab", { name: /^字段/ }));

    // Wait for the columns section to actually render before asserting on
    // its cards (the grain field on the overview tab also contains the
    // column name "order_key" so we cannot use it as a readiness signal).
    await screen.findByText(/每张卡片展示 PK/);

    expect(screen.getByText("order_key")).toBeInTheDocument();
    // Metadata badges
    expect(screen.getAllByText("PK").length).toBeGreaterThan(0);
    expect(screen.getAllByText("string").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Not Null").length).toBeGreaterThan(0);
    expect(screen.getByText("订单行 ID")).toBeInTheDocument();
    // AI text is visible (read-only)
    expect(screen.getByText(/Business key grouping/)).toBeInTheDocument();
    // Adopt AI buttons exist (one per column that has AI; fixture has 2)
    const adoptButtons = screen.getAllByRole("button", { name: /采纳 AI 描述|覆盖为 AI 描述/ });
    expect(adoptButtons.length).toBeGreaterThan(0);
    // Critical: AI must NOT be silently pre-filled into Human textarea on initial render
    expect(
      screen.queryByDisplayValue("Business key grouping multiple line items belonging to one order.")
    ).not.toBeInTheDocument();
  });

  it("adopts AI description into Human textarea and writes human in dry-run patch", async () => {
    const fetchMock = stubEditorFetch();
    renderEditor();

    await openManualSemanticEditor();
    fireEvent.click(screen.getByRole("tab", { name: /^字段/ }));
    await screen.findByText(/每张卡片展示 PK/);

    // The first Adopt button belongs to order_key (the first card with AI
    // and an empty human description).
    const adoptButton = await screen.findByRole("button", { name: "采纳 AI 描述：order_key" });
    fireEvent.click(adoptButton);

    // After click, Human textarea now contains the AI text
    expect(
      await screen.findByDisplayValue(
        "Business key grouping multiple line items belonging to one order."
      )
    ).toBeInTheDocument();

    // Dry-run patch writes only descriptions.human (not the AI bucket)
    await waitFor(() => {
      const putCall = fetchMock.mock.calls.find(
        (call) =>
          call[1]?.method === "PUT" &&
          JSON.parse(String(call[1]?.body)).dryRun === true &&
          JSON.parse(String(call[1]?.body)).patch.columns?.some(
            (column: { name: string; description: string }) =>
              column.name === "order_key" &&
              column.description === "Business key grouping multiple line items belonging to one order."
          )
      );
      expect(putCall).toBeTruthy();
      const body = JSON.parse(String(putCall?.[1]?.body));
      expect(body.dryRun).toBe(true);
      expect(body.patch.columns).toContainEqual({
        name: "order_key",
        description: "Business key grouping multiple line items belonging to one order."
      });
    });
  });

  it("renders sticky change review as pure feedback while the semantic editor is open", async () => {
    stubEditorFetch();
    renderEditor();

    await openManualSemanticEditor();
    const review = await screen.findByTestId("table-editor-change-review");
    expect(review).toHaveTextContent("变更审阅");
    expect(within(review).queryByRole("button", { name: /保存/ })).not.toBeInTheDocument();
    expect(within(review).getByRole("tab", { name: "YAML Diff" })).toBeInTheDocument();
    expect(within(review).getAllByText(/影响文件/).length).toBeGreaterThan(0);
    expect(within(review).getAllByText(/未知 YAML Key/).length).toBeGreaterThan(0);
  });

  it("batch adopts AI descriptions only into selected empty Human fields", async () => {
    const fetchMock = stubEditorFetch();
    renderEditor();

    await openManualSemanticEditor();
    fireEvent.click(screen.getByRole("tab", { name: /^字段/ }));
    await screen.findByTestId("field-batch-toolbar");

    fireEvent.click(screen.getByRole("button", { name: "缺少人工描述" }));
    expect(screen.getByTestId("field-batch-selection-count")).toHaveTextContent("已选 0 / 可见 2");
    fireEvent.click(screen.getByRole("button", { name: "全选筛选结果" }));
    expect(screen.getByTestId("field-batch-selection-count")).toHaveTextContent("已选 2 / 可见 2");
    fireEvent.click(screen.getByRole("button", { name: "批量采纳 AI 描述" }));
    fireEvent.click(screen.getByRole("button", { name: "全部字段" }));

    expect(
      await screen.findByDisplayValue(
        "Business key grouping multiple line items belonging to one order."
      )
    ).toBeInTheDocument();
    expect(screen.getByDisplayValue("Date when the order was placed.")).toBeInTheDocument();
    expect(screen.getByDisplayValue("Unique row identifier")).toBeInTheDocument();
    expect(screen.queryByDisplayValue("Unique row identifier generated by the source system.")).not.toBeInTheDocument();

    await waitFor(() => {
      const dryRunCall = fetchMock.mock.calls.find(
        (call) =>
          call[1]?.method === "PUT" &&
          JSON.parse(String(call[1]?.body)).dryRun === true &&
          JSON.parse(String(call[1]?.body)).patch.columns?.length === 2
      );
      expect(dryRunCall).toBeTruthy();
      const body = JSON.parse(String(dryRunCall?.[1]?.body));
      expect(body.patch.columns).toEqual([
        {
          name: "order_key",
          description: "Business key grouping multiple line items belonging to one order."
        },
        {
          name: "order_date",
          description: "Date when the order was placed."
        }
      ]);
    });
  });

  it("does not write empty Human descriptions for untouched AI-only fields", async () => {
    const fetchMock = stubEditorFetch();
    renderEditor();

    await screen.findByRole("heading", { name: "superstore_orders" });

    await waitFor(() => {
      const dryRunCall = fetchMock.mock.calls.find(
        (call) => call[1]?.method === "PUT" && JSON.parse(String(call[1]?.body)).dryRun === true
      );
      expect(dryRunCall).toBeTruthy();
      const body = JSON.parse(String(dryRunCall?.[1]?.body));
      expect(body.patch.tableDescription).toBeUndefined();
      expect(body.patch.columns).toBeUndefined();
    });
  });

  it("renders Overlay badges with resolved overlay path tooltip", async () => {
    stubEditorFetch();
    renderEditor();

    await openManualSemanticEditor();
    // The overview page already exposes overlay badge for grain and the table grain metadata
    expect(await screen.findAllByText("Overlay")).not.toHaveLength(0);
    // The tooltip should resolve to a concrete overlay path. There can be
    // more than one (grain metadata + grain input) so use getAllByTitle.
    expect(
      screen.getAllByTitle(
        "修改将写入独立 overlay 文件：semantic-layer/mysql-aliyun/superstore_orders.yaml"
      ).length
    ).toBeGreaterThan(0);

    // Measures section also exposes the overlay badge
    fireEvent.click(screen.getByRole("tab", { name: /^指标/ }));
    expect((await screen.findAllByText("Overlay")).length).toBeGreaterThan(0);
    // Segments section too
    fireEvent.click(screen.getByRole("tab", { name: /^分群/ }));
    expect(screen.getAllByText("Overlay").length).toBeGreaterThan(0);
  });

  it("removes prominent candidate suggestions from the table workbench", async () => {
    const fetchMock = stubEditorFetch({
      candidates: [
        {
          conn: "mysql-aliyun",
          schema: "dataforai",
          fromTable: "superstore_orders",
          join: {
            to: "rows",
            on: "superstore_orders.row_id = rows.row_id",
            relationship: "many_to_one",
            source: "candidate"
          },
          confidence: "candidate",
          note: "字段名匹配"
        }
      ]
    });
    renderEditor();

    expect(await screen.findByRole("heading", { name: "superstore_orders" })).toBeInTheDocument();
    expect(screen.queryByTestId("candidate-joins-disclosure")).not.toBeInTheDocument();
    expect(screen.queryByText(/待处理建议/)).not.toBeInTheDocument();
    expect(screen.queryByText(/智能推断的候选关联关系/)).not.toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "确认写入 rows 关联" })).not.toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "保留 rows 为候选关联" })).not.toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "标记 rows 关联不采用" })).not.toBeInTheDocument();
    expect(fetchMock.mock.calls.some((call) => String(call[0]).endsWith("/api/joins/candidates"))).toBe(false);
  });

  it("keeps formal join maintenance available under semantic content", async () => {
    stubEditorFetch();
    renderEditor();

    await openManualSemanticEditor();
    fireEvent.click(screen.getByRole("tab", { name: /^关联/ }));

    expect(await screen.findByText("正式关联关系仍在关联关系页面维护，这里只展示当前表上下文。")).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "打开关联关系" })).toHaveAttribute(
      "href",
      "/joins/mysql-aliyun/dataforai/superstore_orders"
    );
    expect(screen.getByText("当前表还没有正式关联关系。")).toBeInTheDocument();
  });

  it("Cmd+S triggers DryRun and switches to Diff tab, never saves", async () => {
    const fetchMock = stubEditorFetch();
    renderEditor();

    await openManualSemanticEditor();
    // Switch to columns section first so the form has something to dry-run
    fireEvent.click(screen.getByRole("tab", { name: /^字段/ }));
    await screen.findByText(/每张卡片展示 PK/);
    expect(screen.getByText("order_key")).toBeInTheDocument();

    // Find the form root to focus inside
    const form = document.getElementById("table-editor-form");
    expect(form).toBeTruthy();

    // Simulate Cmd+S
    const keyEvent = new KeyboardEvent("keydown", {
      key: "s",
      metaKey: true,
      bubbles: true,
      cancelable: true
    });
    const preventDefaultSpy = vi.spyOn(keyEvent, "preventDefault");
    fireEvent(form as HTMLElement, keyEvent);

    expect(preventDefaultSpy).toHaveBeenCalled();

    // A dry-run PUT should be sent
    await waitFor(() => {
      const dryRunCall = fetchMock.mock.calls.find(
        (call) =>
          call[1]?.method === "PUT" &&
          JSON.parse(String(call[1]?.body)).dryRun === true
      );
      expect(dryRunCall).toBeTruthy();
    });

    // No save with dryRun false should be sent
    const saveCalls = fetchMock.mock.calls.filter((call) => {
      if (call[1]?.method !== "PUT") return false;
      return JSON.parse(String(call[1]?.body)).dryRun === false;
    });
    expect(saveCalls).toHaveLength(0);

    // The Diff tab should be selected
    await waitFor(() => {
      const diffTab = screen.getByRole("tab", { name: "YAML Diff" });
      expect(diffTab).toHaveAttribute("aria-selected", "true");
    });
    expect(toastMock.success).toHaveBeenCalledWith("已更新预览");
    expect(toastMock.error).not.toHaveBeenCalledWith("预览失败");
  });

  it("does not intercept Tab navigation in the table editor form", async () => {
    stubEditorFetch();
    renderEditor();

    await screen.findByRole("heading", { name: "superstore_orders" });
    const form = document.getElementById("table-editor-form");
    expect(form).toBeTruthy();

    const keyEvent = new KeyboardEvent("keydown", {
      key: "Tab",
      bubbles: true,
      cancelable: true
    });
    const preventDefaultSpy = vi.spyOn(keyEvent, "preventDefault");
    fireEvent(form as HTMLElement, keyEvent);

    expect(preventDefaultSpy).not.toHaveBeenCalled();
  });

  it("Cmd+S reports DryRun failure instead of showing a success toast", async () => {
    stubEditorFetch({ failPreview: true });
    renderEditor();

    await screen.findByRole("heading", { name: "superstore_orders" });
    const form = document.getElementById("table-editor-form");
    expect(form).toBeTruthy();

    fireEvent(
      form as HTMLElement,
      new KeyboardEvent("keydown", {
        key: "s",
        metaKey: true,
        bubbles: true,
        cancelable: true
      })
    );

    expect(await screen.findByText("preview denied")).toBeInTheDocument();
    expect(toastMock.error).toHaveBeenCalledWith("预览失败");
    expect(toastMock.success).not.toHaveBeenCalledWith("已更新预览");
  });

  it("saves with dryRun false from the page-level save button", async () => {
    const fetchMock = stubEditorFetch();
    renderEditor();

    fireEvent.click(await screen.findByRole("button", { name: "保存" }));

    await waitFor(() => {
      const saveCall = fetchMock.mock.calls.find((call) => {
        if (call[1]?.method !== "PUT") {
          return false;
        }
        return JSON.parse(String(call[1].body)).dryRun === false;
      });
      expect(saveCall).toBeTruthy();
    });
  });

  it("shows save errors in the inspector", async () => {
    stubEditorFetch({ failSave: true });
    renderEditor();

    fireEvent.click(await screen.findByRole("button", { name: "保存" }));

    expect(await screen.findByText("保存失败：disk denied")).toBeInTheDocument();
  });
});
