services:
  lucy:
    secrets:
      - mysql_password
      - postgres_password

secrets:
  mysql_password:
    file: ./secrets/mysql-password
  postgres_password:
    file: ./secrets/postgres-password
